// new message arrival
#define NTLN_NOTIFICATION_NEW_MESSAGE_RECEIVED @"NTLN_NOTIFICATION_NEW_MESSAGE_RECEIVED"
#define NTLN_NOTIFICATION_NEW_MESSAGE_ADDED @"NTLN_NOTIFICATION_NEW_MESSAGE_ADDED"

// message has been marked as read
// object: a message marked as read or nil (there's no unread message)
#define NTLN_NOTIFICATION_MESSAGE_STATUS_MARKED_AS_READ @"NTLN_NOTIFICATION_MESSAGE_STATUS_MARKED_AS_READ"

// message view change
#define NTLN_NOTIFICATION_MESSAGE_VIEW_CHANGING @"NTLN_NOTIFICATION_MESSAGE_VIEW_CHANGING"
#define NTLN_NOTIFICATION_MESSAGE_VIEW_CHANGED @"NTLN_NOTIFICATION_MESSAGE_VIEW_CHANGED"

// look & feels
#define NTLN_NOTIFICATION_COLOR_SCHEME_CHANGED @"NTLN_NOTIFICATION_COLOR_SCHEME_CHANGED"
#define NTLN_NOTIFICATION_WINDOW_ALPHA_CHANGED @"NTLN_NOTIFICATION_WINDOW_ALPHA_CHANGED"
#define NTLN_NOTIFICATION_FONT_SIZE_CHANGED @"NTLN_NOTIFICATION_FONT_SIZE_CHANGED"
#define NTLN_NOTIFICATION_FONT_SIZE_CHANGED2 @"NTLN_NOTIFICATION_FONT_SIZE_CHANGED2"

// object: true - changed to display / false - change to hide
#define NTLN_NOTIFICATION_STATISTICS_DISPLAY_SETTING_CHANGED @"NTLN_NOTIFICATION_STATISTICS_DISPLAY_SETTING_CHANGED"

#define NTLN_NOTIFICATION_SEND_MESSAGE_WITH_ENTER_AND_MODIFIER_SETTING_CHANGED @"NTLN_NOTIFICATION_SEND_MESSAGE_WITH_ENTER_AND_MODIFIER_SETTING_CHANGED"